all:
	vlna proj3.tex
	latex proj3.tex
	latex proj3.tex
	dvips -t a4 proj3.dvi
	ps2pdf -sPAPERSIZE=a4 proj3.ps	

rm:
	rm proj3.aux
	rm proj3.log
	rm proj3.dvi	
	rm proj3.ps
	rm proj3.te~
	rm proj3.pdf
